local ProvincesMetadata = {
	["Valera Province"] = {
		Wild = {
			["Valera Province Wilds"] = "Valera Province, Wilds",
		},
		Locations = {
			["Shattered Glade"] = "Shattered Glade",
			["The Ironclad Fort"] = "The Ironclad Fort",
			["Whispering Marshes"] = "Whispering Marshes",
		},
		Villages = {
			["Initial Village"] = "Initial Village",
			["Gnomes Abandoned Mine"] = "Gnomes Abandoned Mine",
		},
	},
}

return ProvincesMetadata
